### ISSUE TITLE
Pastelview does not cover 100% of screen width on iphone 6 plus

### ISSUE THREAD

**Issue by kiwo12345** [cruisediary/Pastel#20]
I added a `uiview` using storyboard and gave it a class of `PastelView`

Autolayout contraints:
Top space to superview: 0
Trailing/leading space to superview: 0
Height: 45

More or less a uiview that is 45px high and hugs the top/left/right sides of my view.

ViewdidLoad:

```
self.testview.startPoint = .topRight
self.testview.endPoint = .bottomLeft
self.testview.animationDuration = 3.0
self.testview.setColors(colors: [UIColor(red:0.99, green:0.19, blue:0.35, alpha:1.0),
                                                      UIColor(red:1.00, green:0.37, blue:0.57, alpha:1.0)])
self.testview.startAnimation()
```

When I run the simulator or test it on a real iphone 5 device everything looks fine, but when I run a iphone 6 plus or test it on a real iphone 6 plus device I can see that the gradient view doesnt cover the whole width, it gets to short on the right side:

<img width="218" alt="screen shot 2017-06-01 at 22 19 01" src="https://cloud.githubusercontent.com/assets/10579811/26699224/3ad3c948-4719-11e7-9a22-544e67829485.png">

The gradient animation still works but it doesnt cover 100% of the width.

**Comment by kiwo12345** [comment]
Solved it, insetad of starting the animation in viewdidload:

```
override func viewDidLayoutSubviews() {
      self.testview.startAnimation()
}
```

**Comment by dannymout** [comment]
@kiwo12345 Can you close this issue, as it has been solved.
