### ISSUE TITLE
Swift 4 Version

### ISSUE THREAD

**Issue by ThreadPitt** [cruisediary/Pastel#27]
Hi,

great lib, is there a Swift 4 version planned?

Cheers!

**Comment by sxcore** [comment]
As I can see this is not maintained, I will try to do this on my own fork.

**Comment by avighnash** [comment]
are you going to make a swift 4 version?

**Comment by sxcore** [comment]
I will try my best to do this in this week :)

**Comment by ThreadPitt** [comment]
Yeah, thanks, would be great!

My app uses it for the onboarding: https://itunes.apple.com/us/app/procast-podcast-app/id1215380730


Von: Michał Czerniakowski [mailto:notifications@github.com]
Gesendet: Montag, 15. Januar 2018 09:20
An: cruisediary/Pastel <Pastel@noreply.github.com>
Cc: Thread Pitt <sauvage@web.de>; Author <author@noreply.github.com>
Betreff: Re: [cruisediary/Pastel] Swift 4 Version (#27)


I will try my best to do this in this week :)

**Comment by sxcore** [comment]
PR is in Work In Progress state on #28 :)
