### ISSUE TITLE
QUESTION:  How to put the animation on a continuous loop.  

### ISSUE THREAD

**Issue by jmckosky16** [cruisediary/Pastel#31]
Hi all,

How would I have the animation on a smooth, continuous loop?  Might be something small I'm missing.  Thank you.

**Comment by jmckosky16** [comment]
putting the code in viewDidLoad made it so the animation would not repeat.  However, putting the code in the viewWillAppear solves this issue.  (Putting code in viewDidAppear has a split second lag time for the animation to start.  Putting the pastel in viewWillAppear seems like the best issue.

**Comment by kboy-silvergym** [comment]
@jmckosky16 
I've faced same issue.
And I also resolve this if I put code in viewWillAppear.
Thanks!

By the way, [README](https://github.com/cruisediary/Pastel/blob/master/README.md) should be fixed so that the code is written in viewWillAppear.
