### ISSUE TITLE
Restore state after application enters background.

### ISSUE THREAD

**Issue by iambenmitchell** [cruisediary/Pastel#38]
Wherever someone leaves my app and lets it go into the background, when they then later open the app, the gradient is no longer cycling.

Is there away to restore the state the gradient was in before being sent to background?

thank you.

I think I should be able to do it with `func applicationDidBecomeActive(_ application: UIApplication) {` but I don't know how

**Comment by iambenmitchell** [comment]
override func viewDidLoad() {
        super.viewDidLoad()
        gradient()
        NotificationCenter.default.addObserver(self, selector: #selector(willEnterForeground), name: UIApplication.willEnterForegroundNotification
            , object: nil)
 
    }
    
    @objc func willEnterForeground() {
        print("test")
        gradient()
    }
    
    func gradient(){
        let pastelView = PastelView(frame: view.bounds)
        
        // Custom Direction
        pastelView.startPastelPoint = .bottomLeft
        pastelView.endPastelPoint = .topRight
        
        // Custom Duration
        pastelView.animationDuration = 1.5
        
        // Custom Color
        pastelView.setColors([UIColor(red: 156/255, green: 39/255, blue: 176/255, alpha: 1.0),
                              UIColor(red: 255/255, green: 64/255, blue: 129/255, alpha: 1.0),
                              UIColor(red: 123/255, green: 31/255, blue: 162/255, alpha: 1.0),
                              UIColor(red: 32/255, green: 76/255, blue: 255/255, alpha: 1.0),
                              UIColor(red: 32/255, green: 158/255, blue: 255/255, alpha: 1.0),
                              UIColor(red: 90/255, green: 120/255, blue: 127/255, alpha: 1.0),
                              UIColor(red: 58/255, green: 255/255, blue: 217/255, alpha: 1.0)])
        
        
        pastelView.startAnimation()
        view.insertSubview(pastelView, at: 0)
        print("Test1")
    }
"Test" and "Test1" are printed to the console yet the application refuses to resume the gradient

**Comment by dannmat** [comment]
👍

**Comment by dannmat** [comment]
Also have this issue

**Comment by kaseyb002** [comment]
@MrBenFTW 
You're inserting a new `pastelView` *behind* the ones that are already in there each time you call `gradient()`.

`view.insertSubview(pastelView, at: 0)`

I'd just keep a reference to `pastelView` and reinit each time. Add it to the main view only once.

```swift
// View Controller property
private lazy var pastelView = PastelView(frame: view.bounds)

func restartPastel() {
    pastelView = PastelView(frame: view.bounds)
    pastelView.startAnimation()
}

@objc func willEnterForeground() {
    restartPastel()
}
```
